SET IDENTITY_INSERT [dbo].[Answers] ON
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (1, 1, 'Depends on weather interface Behaviour extends another interface', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (2, 1, 'Yes, any number of interfaces', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (3, 1, 'No, because interface may extend only one interface', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (4, 1, 'Yes, only one interface', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (5, 2, 'null', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (6, 2, 'assert', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (7, 2, 'super', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (8, 2, 'abstract', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (9, 2, 'value', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (10, 3, '4', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (11, 3, '2+4', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (12, 3, '6', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (13, 3, '1+3', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (14, 4, 'ORDER', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (15, 4, 'ORDER BY', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (16, 4, 'SORT BY', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (17, 4, 'SORT', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (18, 5, 'method in class Foo overloads method for class Bar', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (19, 5, 'method in class Foo overrides method for class Bar', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (20, 6, 'List', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (21, 6, 'Map', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (22, 6, 'array', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (23, 6, 'Set', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (24, 7, 'EXTRACT', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (25, 7, 'GET', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (26, 7, 'SELECT', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (27, 7, 'READ', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (28, 8, 'The name of the method and parameters (param names make sense)', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (29, 8, 'The name of the method, parameters and return types', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (30, 8, 'The name of the method and parameters(types and order make sense)', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (31, 8, 'The name of the method, parameters, return types and thrown exceptions', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (32, 9, '2', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (33, 9, '3', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (34, 9, '4', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (35, 9, '5', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (36, 10, 'An abstract definition of an object', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (37, 10, 'An executable piece of code', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (38, 10, 'A varible', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (39, 10, 'An object', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (40, 11, 'false, false', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (41, 11, 'false, true', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (42, 11, 'true, true', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (43, 11, 'true, false', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (44, 12, 'Is only accessible from within the slass', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (45, 12, 'Is accessible publicly', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (46, 12, 'Is accessible by the slass and its subclasses', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (47, 12, 'Is only accessible by other classes of the same package', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (48, 13, 'ar.length', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (49, 13, '1', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (50, 13, 'ar.length - 1', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (51, 13, '0', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (52, 14, 'The try block should be followed by either a catch block or a finally block', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (53, 14, 'The try block should be followed by a catch block', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (54, 14, 'The try block should be followed by a finally block', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (55, 14, 'The try block should be followed by both a catch block and a finally block', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (56, 15, 'Hello World printed 7 times', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (57, 15, 'compilation error', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (58, 15, 'Hello World printed 5 times', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (59, 15, 'Hello World printed 6 times', 0 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (60, 16, 'DELETE is used to delete a resource', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (61, 16, 'POST is used to insert', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (62, 16, 'PUT is used to update', 1 )
INSERT INTO [dbo].[Answers] ([Id], [QuestionId], [Text], [IsCorrect]) VALUES (63, 16, 'GET is used to get the resource', 1 )
SET IDENTITY_INSERT [dbo].[Answers] OFF
